services:
  db:
    image: postgres:16
    container_name: ticket-db
    environment:
      POSTGRES_USER: ticket
      POSTGRES_PASSWORD: ticket
      POSTGRES_DB: ticketdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: